name: poll_power_api_server
description: Little API server for poll power project
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.8
  dartz: ^0.10.1
  dotenv: ^4.2.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.4.0
  injectable_generator: ^2.6.1
  # path: ^1.8.0
  jaguar_jwt: ^3.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  openapi_base: ^1.3.1
  orm: 4.0.2
  uuid: ^4.3.3
  poll_power_openapi:
    git:
      url:
        https://github.com/afraitaneayal/poll_power_api_definition
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

scripts:
  watch: "dart run build_runner watch"
  build: "dart run build_runner build"
  gen: "npx prisma generate"
  push: "npx prisma db push"
  start: "yarn nodemon --exec dart bin/main.dart"